AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.6
  Exclude:
    - 'cns_brazil.gemspec'
    - 'Gemfile'

Metrics/AbcSize:
  Max: 17

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false